/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Almacen;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author tutu5
 */
public class AlmacenF extends javax.swing.JFrame {

    /**
     * Creates new form Almacen
     */
    DefaultListModel modelL;
    ArrayList<Persona> persona;;
    public AlmacenF() {
        initComponents();
        persona = new ArrayList<>();
        modelL = new DefaultListModel();
        lbl_Mensaje.setModel(modelL);
    }

    
    
        public class Nombre extends Persona{

        private double precio;
        
        public Nombre(String nombre){
            super(nombre);
            
        }
        
        @Override
        public int getTipo() {
            return 1;
        }
        
    }
    
    
    
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_padre = new javax.swing.JTextField();
        txt_estudiante = new javax.swing.JTextField();
        txt_profesor = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lbl_Mensaje = new javax.swing.JList<>();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Padre:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        jLabel2.setText("Estudiante:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabel3.setText("Profesor:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));
        getContentPane().add(txt_padre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 200, -1));
        getContentPane().add(txt_estudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 180, -1));
        getContentPane().add(txt_profesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 190, -1));

        jButton3.setText("Agregar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, -1, -1));

        jScrollPane1.setViewportView(lbl_Mensaje);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, 160, 220));

        jButton4.setText("Agregar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, -1, -1));

        jButton5.setText("Agregar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        if (!this.txt_estudiante.getText().trim().isEmpty()) {
            
            persona.add(new Nombre(this.txt_estudiante.getText().trim()));

            int a = persona.size();
            this.txt_estudiante.setText("");
            JOptionPane.showMessageDialog(null, "Bienvenido Estudiante");
            llenarLista();
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (!this.txt_padre.getText().trim().isEmpty()) {
            
            persona.add(new Nombre(this.txt_padre.getText().trim()));

            int a = persona.size();
            this.txt_padre.setText("");
            JOptionPane.showMessageDialog(null, "Bienvenido Padre de familia");
            llenarLista();
        } 
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if (!this.txt_profesor.getText().trim().isEmpty()) {
            
            persona.add(new Nombre(this.txt_profesor.getText().trim()));

            int a = persona.size();
            this.txt_profesor.setText("");
            JOptionPane.showMessageDialog(null, "Bienvenido Profesor");
            llenarLista();
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    
        private void llenarLista(){
        
        modelL = new DefaultListModel();
        
        for (int i = 0; i < persona.size(); i++) {
            
            modelL.addElement(persona.get(i).getNombre());
            
        }
        lbl_Mensaje.setModel(modelL);
    } 
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlmacenF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlmacenF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlmacenF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlmacenF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlmacenF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lbl_Mensaje;
    private javax.swing.JTextField txt_estudiante;
    private javax.swing.JTextField txt_padre;
    private javax.swing.JTextField txt_profesor;
    // End of variables declaration//GEN-END:variables
}
